package vista;

import clases.Convocatoria;
import clases.Enunciado;
import controlador.Controlador;
import excepciones.ErrConsultar;
import excepciones.ErrCrear;
import excepciones.ErrExtra;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Esta ventan permite al usuario asignar un enunciado a una convocatoria de
 * examen.
 *
 * @author Jason.
 */
public class AsignarEnunciado extends javax.swing.JDialog {

    private Controlador controlador;
    private List<Convocatoria> convocatorias;
    private List<Enunciado> enunciados;

    /**
     * Crea la ventana AsignarEnunciado.
     *
     * @param parent la ventana padre.
     * @param modal si es modal.
     * @param controlador el controlador de la aplicacion.
     */
    public AsignarEnunciado(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;

        try {
            enunciados = controlador.listarEnunciados();
            convocatorias = controlador.listarConvocatorias();

            for (Convocatoria convocatoria : convocatorias) {
                cbConvocatoria.addItem(convocatoria.getConvocatoria() + "");
            }

            for (Enunciado enunciado : enunciados) {
                cbEnunciado.addItem(enunciado.getId() + "");
            }
            cbConvocatoria.setSelectedIndex(-1);
            cbEnunciado.setSelectedIndex(-1);

        } catch (ErrConsultar ex) {
            ex.mostrarError();
        } catch (ErrExtra ex) {
            Logger.getLogger(AsignarEnunciado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblConvocatoria = new javax.swing.JLabel();
        cbConvocatoria = new javax.swing.JComboBox<>();
        lblEnunciado = new javax.swing.JLabel();
        cbEnunciado = new javax.swing.JComboBox<>();
        btnAsignar = new excepciones.Button();
        btnVolver = new excepciones.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 51, 53));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(227, 227, 227));
        lblTitulo.setText("ASIGNAR ENUNCIADO A CONVOCATORIA");

        lblConvocatoria.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblConvocatoria.setForeground(new java.awt.Color(227, 227, 227));
        lblConvocatoria.setText("Unidad didactica:");

        cbConvocatoria.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblEnunciado.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblEnunciado.setForeground(new java.awt.Color(227, 227, 227));
        lblEnunciado.setText("Enunciado:");

        cbEnunciado.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnVolver.setText("<---");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConvocatoria)
                            .addComponent(lblEnunciado))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnunciado)
                    .addComponent(cbEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConvocatoria))
                .addGap(53, 53, 53)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Si pulsa el boton asignara un examen a una convocatoria de examen.
     *
     * @param evt
     */
    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        try {
            Convocatoria convocatoria = convocatorias.get(cbConvocatoria.getSelectedIndex());
            convocatoria.setIdEnunciado(enunciados.get(cbEnunciado.getSelectedIndex()).getId());
            controlador.asignarEnunciado(convocatoria);

        } catch (ErrCrear ex) {
            ex.mostrarError();
        } catch (ErrExtra ex) {
            ex.mostrarError();
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * Vuelve a la pantalla inicial.
     *
     * @param evt
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        VMain vMain = new VMain(controlador);
        vMain.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private excepciones.Button btnAsignar;
    private excepciones.Button btnVolver;
    private javax.swing.JComboBox<String> cbConvocatoria;
    private javax.swing.JComboBox<String> cbEnunciado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConvocatoria;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
