package vista;

import clases.Enunciado;
import clases.UnidadDidactica;
import controlador.Controlador;
import excepciones.ErrConsultar;
import excepciones.ErrCrear;
import excepciones.ErrExtra;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Esta ventana permite al usuario asignar una unidad didactica a un enunciado.
 *
 * @author Jason.
 */
public class AsignarUnidad extends javax.swing.JDialog {

    private Controlador controlador;
    private List<UnidadDidactica> unidadesDidacticas;
    private List<Enunciado> enunciados;

    /**
     * Crea la ventana AsignarUnidad
     *
     * @param parent la ventana padre.
     * @param modal si es modal.
     * @param controlador el controlador de la aplicacion.
     */
    public AsignarUnidad(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;

        try {
            enunciados = controlador.listarEnunciados();
            unidadesDidacticas = controlador.listarUnidades();

            for (UnidadDidactica unidadesDidactica : unidadesDidacticas) {
                cbUnidad.addItem(unidadesDidactica.getId() + "");
            }

            for (Enunciado enunciado : enunciados) {
                cbEnunciado.addItem(enunciado.getId() + "");
            }
            cbUnidad.setSelectedIndex(-1);
            cbEnunciado.setSelectedIndex(-1);

        } catch (ErrConsultar ex) {
            ex.mostrarError();

        } catch (ErrExtra ex) {
            ex.mostrarError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUnidad = new javax.swing.JLabel();
        cbUnidad = new javax.swing.JComboBox<>();
        lblEnunciado = new javax.swing.JLabel();
        cbEnunciado = new javax.swing.JComboBox<>();
        btnAsignar = new excepciones.Button();
        btnVolver = new excepciones.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 51, 53));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(227, 227, 227));
        lblTitulo.setText("ASIGNAR UNIDAD DIDACTICA A ENUNCIADO");

        lblUnidad.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblUnidad.setForeground(new java.awt.Color(227, 227, 227));
        lblUnidad.setText("Unidad didactica:");

        cbUnidad.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblEnunciado.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblEnunciado.setForeground(new java.awt.Color(227, 227, 227));
        lblEnunciado.setText("Enunciado:");

        cbEnunciado.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnVolver.setText("<---");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblTitulo)
                            .addGap(18, 18, 18))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUnidad)
                                .addComponent(lblEnunciado))
                            .addGap(53, 53, 53)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbEnunciado, 0, 240, Short.MAX_VALUE)
                                .addComponent(cbUnidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidad)
                    .addComponent(cbUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnunciado))
                .addGap(47, 47, 47)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Si se pulsa el boton asignara una unidad didactica a un enunciado.
     *
     * @param evt
     */
    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        try {
            int unidad = unidadesDidacticas.get(cbUnidad.getSelectedIndex()).getId();
            int enunciado = enunciados.get(cbEnunciado.getSelectedIndex()).getId();
            controlador.asignarUnidad(unidad, enunciado);
        } catch (ErrCrear ex) {
            ex.mostrarError();

        } catch (ErrExtra ex) {
            ex.mostrarError();
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * Vuelve a la ventana inical.
     *
     * @param evt
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        VMain vMain = new VMain(controlador);
        vMain.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private excepciones.Button btnAsignar;
    private excepciones.Button btnVolver;
    private javax.swing.JComboBox<String> cbEnunciado;
    private javax.swing.JComboBox<String> cbUnidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidad;
    // End of variables declaration//GEN-END:variables
}
