/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import clases.Dificultad;
import clases.Enunciado;
import controlador.Controlador;

/**
 *
 * @author Jason.
 */
public class CrearEnunciado extends javax.swing.JDialog {

    private Controlador con;

    /**
     * Creates new form CrearEnunciado
     */
    public CrearEnunciado(java.awt.Frame parent, boolean modal, Controlador con) {
        super(parent, modal);
        initComponents();
        this.con = con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngDisponible = new javax.swing.ButtonGroup();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lblDisponible = new javax.swing.JLabel();
        txtNivel = new javax.swing.JComboBox<>();
        rdbtnSi = new javax.swing.JRadioButton();
        rdbtnNo = new javax.swing.JRadioButton();
        txtRuta = new javax.swing.JTextField();
        lblRuta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblId.setText("ID:");

        txtId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblDescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripcion:");

        txtDescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbl1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl1.setText("Nivel:");

        lblDisponible.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDisponible.setText("Disponible:");

        txtNivel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Media", "Baja" }));

        btngDisponible.add(rdbtnSi);
        rdbtnSi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdbtnSi.setText("Si");

        btngDisponible.add(rdbtnNo);
        rdbtnNo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdbtnNo.setText("No");

        txtRuta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblRuta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblRuta.setText("Ruta:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("CREAR ENUNCIADO");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(lbl1)
                            .addComponent(lblRuta)
                            .addComponent(lblDisponible))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdbtnSi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdbtnNo))
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txtNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnSi)
                    .addComponent(rdbtnNo)
                    .addComponent(lblDisponible))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtId.setText("");
        txtDescripcion.setText("");
        txtNivel.setSelectedIndex(-1);
        rdbtnSi.setSelected(false);
        rdbtnNo.setSelected(false);
        txtRuta.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (this.validarDatos()) {
            Enunciado enunciado = new Enunciado();
            enunciado.setId(Integer.parseInt(txtId.getText()));
            enunciado.setDescripcion(txtDescripcion.getText());

            enunciado.setDisponible(rdbtnSi.isSelected());
            enunciado.setRuta(txtRuta.getText());

            switch (txtNivel.getSelectedIndex()) {
                case 0:
                    enunciado.setNivel(Dificultad.ALTA);
                    break;
                case 1:
                    enunciado.setNivel(Dificultad.MEDIA);
                    break;
                case 2:
                    enunciado.setNivel(Dificultad.BAJA);
                    break;
                default:
                    System.out.println("Seleciona un nivel --> " + txtNivel.getSelectedIndex());
            }

            con.crearEnunciado(enunciado);
        }

    }//GEN-LAST:event_btnEnviarActionPerformed

    public boolean validarDatos() {
        boolean valido = true;

        try {
            Integer.parseInt(txtId.getText());

        } catch (NumberFormatException e) {
            valido = false;
            System.out.println("Eso no es un numero");
        }

        if (txtNivel.getSelectedIndex() == -1) {
            valido = false;
            System.out.println("Elige un nivel");
        }

        if (!rdbtnSi.isSelected() == !rdbtnNo.isSelected()) {
            valido = false;
            System.out.println("Es disponible?");
        }

        return valido;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup btngDisponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JRadioButton rdbtnNo;
    private javax.swing.JRadioButton rdbtnSi;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JComboBox<String> txtNivel;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
