package vista;

import controlador.Controlador;

/**
 * Esta ventana permite acceder al resto de ventanas.
 *
 * @author Jason.
 */
public class VMain extends javax.swing.JFrame {

    private Controlador controlador;

    /**
     * Crea la ventana VMain
     *
     * @param controlador
     */
    public VMain(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        btnCrearEnunciado = new excepciones.Button();
        btnCrearUnidad = new excepciones.Button();
        btnCrearConvocatoria = new excepciones.Button();
        btnConsultarEnunciado = new excepciones.Button();
        btnConsultarUnidad = new excepciones.Button();
        btnConsultarConvocatoria = new excepciones.Button();
        btnAsignarUnidad = new excepciones.Button();
        btnAsignarEnunciado = new excepciones.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(49, 51, 53));

        fondo.setBackground(new java.awt.Color(49, 51, 53));

        btnCrearEnunciado.setText("Crear Enunciado");
        btnCrearEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEnunciadoActionPerformed(evt);
            }
        });

        btnCrearUnidad.setText("Crear Unidad");
        btnCrearUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUnidadActionPerformed(evt);
            }
        });

        btnCrearConvocatoria.setText("Crear Convocatoria");
        btnCrearConvocatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearConvocatoriaActionPerformed(evt);
            }
        });

        btnConsultarEnunciado.setText("Consultar Enunciado");
        btnConsultarEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEnunciadoActionPerformed(evt);
            }
        });

        btnConsultarUnidad.setText("Consultar Unidad");
        btnConsultarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarUnidadActionPerformed(evt);
            }
        });

        btnConsultarConvocatoria.setText("Consultar Convocatoria");
        btnConsultarConvocatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarConvocatoriaActionPerformed(evt);
            }
        });

        btnAsignarUnidad.setText("Asignar Unidad");
        btnAsignarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUnidadActionPerformed(evt);
            }
        });

        btnAsignarEnunciado.setText("Asignar Enunciado");
        btnAsignarEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarEnunciadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(btnAsignarUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsignarEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(btnCrearEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnConsultarEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrearConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsultarConvocatoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignarEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre la ventana CrearEnunciado.
     *
     * @param evt
     */
    private void btnCrearEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEnunciadoActionPerformed
        this.dispose();
        CrearEnunciado crearEnunciado = new CrearEnunciado(this, true, controlador);
        crearEnunciado.setVisible(true);
    }//GEN-LAST:event_btnCrearEnunciadoActionPerformed

    /**
     * Abre la ventana CrearUnidadDidactica.
     *
     * @param evt
     */
    private void btnCrearUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUnidadActionPerformed
        this.dispose();
        CrearUnidadDidactica unidadDidactica = new CrearUnidadDidactica(this, true, controlador);
        unidadDidactica.setVisible(true);
    }//GEN-LAST:event_btnCrearUnidadActionPerformed

    /**
     * Abre la ventana CrearConvocatoria.
     *
     * @param evt
     */
    private void btnCrearConvocatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearConvocatoriaActionPerformed
        this.dispose();
        CrearConvocatoria crearConvocatoria = new CrearConvocatoria(this, true, controlador);
        crearConvocatoria.setVisible(true);
    }//GEN-LAST:event_btnCrearConvocatoriaActionPerformed

    /**
     * Abre la ventana ConsultarEnunciado.
     *
     * @param evt
     */
    private void btnConsultarEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEnunciadoActionPerformed
        this.dispose();
        ConsultarEnunciado consultarEnunciado = new ConsultarEnunciado(this, true, controlador);
        consultarEnunciado.setVisible(true);
    }//GEN-LAST:event_btnConsultarEnunciadoActionPerformed

    /**
     * Abre la ventana ConsultarUnidad.
     *
     * @param evt
     */
    private void btnConsultarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarUnidadActionPerformed

    }//GEN-LAST:event_btnConsultarUnidadActionPerformed

    /**
     * Abre la ventana ConsultarConvocatoria .
     *
     * @param evt
     */
    private void btnConsultarConvocatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarConvocatoriaActionPerformed
        this.dispose();
        ConsultarConvocatoria consultarConvocatoria = new ConsultarConvocatoria(this, true, controlador);
        consultarConvocatoria.setVisible(true);
    }//GEN-LAST:event_btnConsultarConvocatoriaActionPerformed

    /**
     * Abre la ventana AsignarUnidad.
     *
     * @param evt
     */
    private void btnAsignarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUnidadActionPerformed
        this.dispose();
        AsignarUnidad asignarUnidad = new AsignarUnidad(this, true, controlador);
        asignarUnidad.setVisible(true);
    }//GEN-LAST:event_btnAsignarUnidadActionPerformed

    /**
     * Abre la ventana AsignarEnunciado.
     *
     * @param evt
     */
    private void btnAsignarEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarEnunciadoActionPerformed
        this.dispose();
        AsignarEnunciado asignarEnunciado = new AsignarEnunciado(this, true, controlador);
        asignarEnunciado.setVisible(true);
    }//GEN-LAST:event_btnAsignarEnunciadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private excepciones.Button btnAsignarEnunciado;
    private excepciones.Button btnAsignarUnidad;
    private excepciones.Button btnConsultarConvocatoria;
    private excepciones.Button btnConsultarEnunciado;
    private excepciones.Button btnConsultarUnidad;
    private excepciones.Button btnCrearConvocatoria;
    private excepciones.Button btnCrearEnunciado;
    private excepciones.Button btnCrearUnidad;
    private javax.swing.JPanel fondo;
    // End of variables declaration//GEN-END:variables
}
