/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author Jason.
 */
public class VMain extends javax.swing.JFrame {

    private Controlador controlador;

    /**
     * Creates new form VMain
     */
    public VMain(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrearEnunciado = new excepciones.Button();
        btnCrearUnidad = new excepciones.Button();
        btnCrearConvocatoria = new excepciones.Button();
        btnConsultarEnunciado = new excepciones.Button();
        btnConsultarUnidad = new excepciones.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(49, 51, 53));

        jPanel1.setBackground(new java.awt.Color(49, 51, 53));

        btnCrearEnunciado.setText("Crear Enunciado");
        btnCrearEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEnunciadoActionPerformed(evt);
            }
        });

        btnCrearUnidad.setText("Crear Unidad");
        btnCrearUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUnidadActionPerformed(evt);
            }
        });

        btnCrearConvocatoria.setText("Crear Convocatoria");
        btnCrearConvocatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearConvocatoriaActionPerformed(evt);
            }
        });

        btnConsultarEnunciado.setText("Consultar Enunciado");
        btnConsultarEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEnunciadoActionPerformed(evt);
            }
        });

        btnConsultarUnidad.setText("Consultar Unidad");
        btnConsultarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarUnidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrearConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCrearUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCrearEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnConsultarEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnCrearUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(btnCrearConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEnunciadoActionPerformed
        this.dispose();
        CrearEnunciado crearEnunciado = new CrearEnunciado(this, true, controlador);
        crearEnunciado.setVisible(true);
    }//GEN-LAST:event_btnCrearEnunciadoActionPerformed

    private void btnCrearUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUnidadActionPerformed
       this.dispose();
        UnidadDidacticaV crearUnidad = new UnidadDidacticaV(this, true, controlador);
        crearUnidad.setVisible(true);
    }//GEN-LAST:event_btnCrearUnidadActionPerformed

    private void btnCrearConvocatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearConvocatoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearConvocatoriaActionPerformed

    private void btnConsultarEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEnunciadoActionPerformed
        this.dispose();
        ConsultarEnunciado consultarEnunciado = new ConsultarEnunciado(this, true, controlador);
        consultarEnunciado.setVisible(true);
    }//GEN-LAST:event_btnConsultarEnunciadoActionPerformed

    private void btnConsultarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarUnidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private excepciones.Button btnConsultarEnunciado;
    private excepciones.Button btnConsultarUnidad;
    private excepciones.Button btnCrearConvocatoria;
    private excepciones.Button btnCrearEnunciado;
    private excepciones.Button btnCrearUnidad;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
